### ISSUE TITLE
Confusing Strings 

### ISSUE THREAD

**Issue by Warhammer4000** [Studio-23-xyz/ButtonIconResourceManager#1]
There's literally no documentation on what the strings should be that we need to call. Either make a list of keys in the document that can be used as a reference. Or better just use enums instead. 

For platforms 

1. Xbox
2. Playstation

For Buttons

1. ButtonEast
2. ButtonWest 
....

And so on.

**Comment by N-Evan** [comment]
Documentation has been updated according to new changes made in the system. Please refer to the following [tag](https://github.com/Studio-23-xyz/ButtonIconResourceManager/releases/tag/v2.0.0) for related changes and fixes.
